name: fuel_management
description: A new Flutter project.
publish_to: "none"
version: 0.0.2+2

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0

  flex_color_scheme: ^7.3.1
  auto_route: ^7.8.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  injectable: ^2.3.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  paged_datatable: ^1.4.3
  async_button_builder: ^3.0.0+1
  drop_down_search_field: ^1.0.0

  #* postgrest *#
  postgrest: ^1.5.1
  #* postgrest *#

  #* FormBuilder *#
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  form_builder_extra_fields: ^10.1.0
  dropdown_search: ^5.0.6
  #* FormBuilder *#

  timezone: ^0.9.2
  event_bus: ^2.0.0
  flutter_pos_printer_platform:
    path: ./pos_printer_platform

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  freezed: ^2.4.3
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
