name: flutter_pos_printer_platform
description: A flutter plugin that prints esc commands to printers in different platforms such as android, ios, windows and different interfaces Bluetooth and BLE, TCP and USB
version: 1.4.1

environment:
  sdk: ">=2.18.4 <3.3.10"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_star_prnt: ^2.3.6
  enum_to_string: ^2.0.1
  image: ^4.0.15

  network_info_plus: ^3.0.2
  ping_discover_network_forked: ^0.0.1
  rxdart: ^0.27.7
  gbk_codec: ^0.4.0
  hex: ^0.2.0
  dart_ping: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.sersoluciones.flutter_pos_printer_platform
        pluginClass: FlutterPosPrinterPlatformPlugin
      ios:
        pluginClass: FlutterPosPrinterPlatformPlugin
      windows:
        pluginClass: FlutterPosPrinterPlatformPlugin

  assets:
    - assets/resources/capabilities.json
    - packages/flutter_pos_printer_platform/resources/capabilities.json
